nguage: go

go:
  - 1.7
  - tip

matrix:
    allow_failures:
        - go: tip

install:
  - go get -v srcd.works/go-parse-utils.v1
  - go get -t -v ./...

script:
  - go test -covermode=atomic -coverprofile=coverage.txt -v .

after_success:
  - bash <(curl -s https://codecov.io$/bash)
